import pkg from "whatsapp-web.js";
const { Client, LocalAuth } = pkg;
import bus from "../bus/index.js";
import sessionManager from "../session/index.js";
import { logger, formatWhatsAppMarkdown } from "../utils/index.js";
import qrcode from "qrcode-terminal";
import path from "node:path";

class SessionState {
  constructor() {
    this.activeSubagents = 0;
    this.statusMsg = null;
    this.lastUserMsg = null;
    this.pendingQuestion = null;
    this.isStreaming = false;
    this.streamText = "";
    this.streamMsg = null;
    this.streamTimer = null;
    this.lastEditTime = 0;
    this.toolsRun = [];
  }
}

class WhatsAppChannel {
  constructor(config = {}) {
    this.enabled = config.enabled === true;
    this.selfChatOnly = config.selfChatOnly === true;
    this.projectName = config.projectName;
    this.debug = config.debug === true;
    this.client = null;
    this.sessions = new Map();
    this.sentMessageIds = new Set();
    this.startTime = Math.floor(Date.now() / 1000);
  }

  async updateProgressMessage(sessionId) {
    const session = this.sessions.get(sessionId);
    if (!session || !session.statusMsg) return;

    let text = `⏳ *Jared is working...*`;
    if (session.activeSubagents > 0) {
      const taskWord = session.activeSubagents === 1 ? "task" : "tasks";
      text += ` _(${session.activeSubagents} active background ${taskWord})_`;
    }

    if (session.toolsRun.length > 0) {
      const lastTool = session.toolsRun[session.toolsRun.length - 1];
      text += `\n• *Last tool:* \`${lastTool}\``;
    }

    try {
      await session.statusMsg.edit(text);
    } catch (e) {
      logger.error("WhatsApp edit progress message error:", e);
    }
  }

  throttleStreamEdit(sessionId) {
    const session = this.sessions.get(sessionId);
    if (!session) return;

    const now = Date.now();
    const waitTime = 1500;
    const timeSinceLastEdit = now - session.lastEditTime;

    if (session.streamTimer) {
      return;
    }

    const performEdit = async () => {
      session.streamTimer = null;
      session.lastEditTime = Date.now();

      const formatted = formatWhatsAppMarkdown(session.streamText);
      const streamContent = `*🤖 Jared is typing...*\n\n${formatted || "..."}`;
      if (!session.streamMsg) {
        try {
          if (session.lastUserMsg) {
            session.streamMsg = await session.lastUserMsg.reply(streamContent);
            this.sentMessageIds.add(session.streamMsg.id.id);
          }
        } catch (e) {
          logger.error("WhatsApp create stream message error:", e);
        }
      } else {
        try {
          await session.streamMsg.edit(streamContent);
        } catch (e) {
          logger.error("WhatsApp edit stream message error:", e);
        }
      }
    };

    if (timeSinceLastEdit >= waitTime) {
      performEdit();
    } else {
      session.streamTimer = setTimeout(
        performEdit,
        waitTime - timeSinceLastEdit
      );
    }
  }

  start() {
    if (!this.enabled) return;

    const authPath = this.projectName
      ? path.join(process.cwd(), ".jared", this.projectName, ".wwebjs_auth")
      : path.join(process.cwd(), ".jared", ".wwebjs_auth");

    const cachePath = this.projectName
      ? path.join(process.cwd(), ".jared", this.projectName, ".wwebjs_cache")
      : path.join(process.cwd(), ".jared", ".wwebjs_cache");

    this.client = new Client({
      authStrategy: new LocalAuth({ dataPath: authPath }),
      webVersionCache: {
        type: "local",
        path: cachePath
      }
    });

    this.client.on("qr", qr => {
      logger.info("WhatsApp QR generated - please scan:");
      qrcode.generate(qr, { small: true });
    });

    this.client.on("ready", () => {
      logger.info("WhatsApp channel connected!");
    });

    this.client.on("message_create", async msg => {
      if (msg.from === "status@broadcast") return;

      // Ignore backlogged messages sent before Jared started to avoid mismatch/race conditions
      if (msg.timestamp && msg.timestamp < this.startTime - 10) {
        return;
      }

      // Ignore automated messages generated by Jared to prevent infinite self-chat loops
      if (msg.body) {
        const body = msg.body;
        if (
          body.startsWith("⏳ *Jared") ||
          body.startsWith("✅ *Jared") ||
          body.startsWith("*🤖 Jared") ||
          body.startsWith("🤖 Jared") ||
          body.startsWith("🔒 *[EXEC GUARD]*")
        ) {
          return;
        }
      }

      if (this.sentMessageIds.has(msg.id.id)) {
        this.sentMessageIds.delete(msg.id.id);
        return;
      }

      const myJID = this.client.info?.wid?._serialized;
      const chatJID = msg.fromMe ? msg.to : msg.from;
      if (this.debug) {
        logger.info(
          `[WhatsApp Debug] msg.fromMe=${msg.fromMe}, msg.from=${msg.from}, msg.to=${msg.to}, chatJID=${chatJID}, myJID=${myJID}`
        );
      }

      let isSelfChat = false;
      try {
        const contact = await this.client.getContactById(chatJID);
        isSelfChat = contact.isMe === true;

        if (!isSelfChat && this.client.pupPage) {
          isSelfChat = await this.client.pupPage.evaluate(jid => {
            const mePn = window.Store.User.getMaybeMePnUser();
            const meLid = window.Store.User.getMaybeMeLidUser();
            const pnStr = mePn ? mePn._serialized || mePn.toString() : null;
            const lidStr = meLid ? meLid._serialized || meLid.toString() : null;
            return jid === pnStr || jid === lidStr;
          }, chatJID);
        }
      } catch (err) {
        logger.error("Error checking contact identity:", err);
      }

      if (this.selfChatOnly && !isSelfChat) return;
      if (msg.fromMe && !isSelfChat) return;

      const sessionId = sessionManager.getSessionId("whatsapp", chatJID);
      let session = this.sessions.get(sessionId);
      if (!session) {
        session = new SessionState();
        this.sessions.set(sessionId, session);
      }
      session.lastUserMsg = msg;

      if (session.pendingQuestion) {
        const callback = session.pendingQuestion;
        session.pendingQuestion = null;
        callback(msg.body);
        return;
      }

      bus.emit("message:received", {
        channel: "whatsapp",
        userId: chatJID,
        sessionId: sessionId,
        content: msg.body,
        meta: { msgObject: msg }
      });
    });

    // Subagent state tracking
    bus.on("subagent:start", payload => {
      if (payload.channel === "whatsapp") {
        const session = this.sessions.get(payload.sessionId);
        if (session) {
          session.activeSubagents++;
          this.updateProgressMessage(payload.sessionId);
        }
      }
    });

    bus.on("subagent:end", payload => {
      if (payload.channel === "whatsapp") {
        const session = this.sessions.get(payload.sessionId);
        if (session) {
          session.activeSubagents = Math.max(0, session.activeSubagents - 1);
          this.updateProgressMessage(payload.sessionId);
        }
      }
    });

    // Task and Tool execution progress
    bus.on("task:start", async payload => {
      if (!payload || !payload.sessionId) return;
      const session = this.sessions.get(payload.sessionId);
      if (session && session.lastUserMsg) {
        try {
          const chat = await session.lastUserMsg.getChat();
          await chat.sendStateTyping();

          session.toolsRun = [];
          const msg = await session.lastUserMsg.reply(
            "⏳ *Jared is starting...*"
          );
          this.sentMessageIds.add(msg.id.id);
          session.statusMsg = msg;
        } catch (e) {
          logger.error("WhatsApp task:start error:", e);
        }
      }
    });

    bus.on("tool:start", async payload => {
      if (!payload || !payload.sessionId) return;
      const session = this.sessions.get(payload.sessionId);
      if (session) {
        let toolStr = payload.name;
        try {
          const args =
            typeof payload.args === "string"
              ? JSON.parse(payload.args)
              : payload.args;
          if (
            args &&
            typeof args === "object" &&
            Object.keys(args).length > 0
          ) {
            let val = String(Object.values(args)[0]).replace(/\n/g, " ");
            if (val.length > 30) val = val.substring(0, 27) + "...";
            toolStr = `${payload.name} (${val})`;
          }
        } catch (e) {}

        session.toolsRun.push(toolStr);
        this.updateProgressMessage(payload.sessionId);
      }
    });

    bus.on("task:end", async payload => {
      if (!payload || !payload.sessionId) return;
      const session = this.sessions.get(payload.sessionId);
      if (session) {
        try {
          if (session.lastUserMsg) {
            const chat = await session.lastUserMsg.getChat();
            await chat.clearState();
          }
          if (session.statusMsg) {
            let content = `✅ *Jared: Task complete*`;
            if (session.toolsRun.length > 0) {
              content +=
                `\n\n*Executed tools:*\n` +
                session.toolsRun.map(t => `• \`${t}\``).join("\n");
            }
            await session.statusMsg.edit(content);
          }
        } catch (e) {
          logger.error("WhatsApp task:end error:", e);
        }
      }
    });

    // Stream token handling
    bus.on("message:stream", async payload => {
      if (payload.channel === "whatsapp") {
        const session = this.sessions.get(payload.sessionId);
        if (session) {
          session.isStreaming = true;
          session.streamText += payload.token;
          this.throttleStreamEdit(payload.sessionId);
        }
      }
    });

    // Send final message response
    bus.on("message:send", async payload => {
      if (payload.channel === "whatsapp") {
        const session = this.sessions.get(payload.sessionId);
        const formattedContent = formatWhatsAppMarkdown(payload.content);

        let header = "";
        if (payload.attempt === 1) {
          header = `*🤖 Jared (Initial Answer):*\n\n`;
        } else if (payload.attempt > 1) {
          header = `*🤖 Jared (Final Answer):*\n\n`;
        } else {
          header = `*🤖 Jared:*\n\n`;
        }

        let footer = "";
        if (payload.usage) {
          const { promptTokens, completionTokens } = payload.usage;
          const total = promptTokens + completionTokens;
          footer = `\n\n_⟡ ${promptTokens.toLocaleString()} input · ${completionTokens.toLocaleString()} output · ${total.toLocaleString()} total tokens_`;
        }

        const fullMsg = header + formattedContent + footer;

        try {
          if (session && session.streamMsg) {
            if (session.streamTimer) {
              clearTimeout(session.streamTimer);
              session.streamTimer = null;
            }
            await session.streamMsg.edit(fullMsg);
            session.streamMsg = null;
            session.isStreaming = false;
            session.streamText = "";
          } else {
            if (payload.meta?.msgObject) {
              const sent = await payload.meta.msgObject.reply(fullMsg);
              this.sentMessageIds.add(sent.id.id);
            } else if (this.client) {
              // Fallback to sending to user ID if msgObject is not available
              let targetJid = payload.userId;
              if (targetJid === "system" || targetJid === "local_user" || !targetJid || !targetJid.includes("@")) {
                if (this.selfChatOnly && this.client.info?.wid?._serialized) {
                  targetJid = this.client.info.wid._serialized;
                } else {
                  // Find the most recent active session
                  let lastMsgTime = 0;
                  let fallbackJid = null;
                  for (const [, sess] of this.sessions.entries()) {
                    if (sess.lastUserMsg && sess.lastUserMsg.timestamp > lastMsgTime) {
                      lastMsgTime = sess.lastUserMsg.timestamp;
                      fallbackJid = sess.lastUserMsg.fromMe ? sess.lastUserMsg.to : sess.lastUserMsg.from;
                    }
                  }
                  if (fallbackJid) {
                    targetJid = fallbackJid;
                  }
                }
              }
              if (targetJid && targetJid.includes("@")) {
                const sent = await this.client.sendMessage(
                  targetJid,
                  fullMsg
                );
                this.sentMessageIds.add(sent.id.id);
              } else {
                logger.error("WhatsApp: No valid recipient JID found for outgoing message.");
              }
            }
          }
        } catch (e) {
          logger.error("WhatsApp send error:", e);
        }
      }
    });

    // Interactive Question Confirmations (e.g. ExecGuard)
    bus.on("console:question", async payload => {
      if (payload.channel === "whatsapp") {
        payload.handled = true;
        const session = this.sessions.get(payload.sessionId);
        if (session) {
          try {
            const cleanPrompt = payload.promptText
              .replace(/\x1b\[[0-9;]*m/g, "")
              .trim();
            const formattedPrompt = `🔒 *[EXEC GUARD]*\n${cleanPrompt}`;

            if (session.lastUserMsg) {
              const sent = await session.lastUserMsg.reply(formattedPrompt);
              this.sentMessageIds.add(sent.id.id);
            } else if (this.client) {
              const sent = await this.client.sendMessage(
                payload.userId,
                formattedPrompt
              );
              this.sentMessageIds.add(sent.id.id);
            }

            session.pendingQuestion = payload.callback;
          } catch (e) {
            logger.error("WhatsApp exec guard prompt error:", e);
            payload.callback("no");
          }
        }
      }
    });

    this.client.initialize().catch(err => {
      logger.error("WhatsApp failed to initialize:", err);
    });
  }

  async stop() {
    if (this.client) {
      try {
        await this.client.destroy();
        logger.info("WhatsApp client destroyed successfully.");
      } catch (err) {
        logger.error("Error destroying WhatsApp client:", err);
      }
    }
  }
}

export { formatWhatsAppMarkdown };
export default WhatsAppChannel;
